name: update

on:
  push:
    branches:
      - main
    paths:
      - "zenn/*"
      - ".github/workflows/zenn-update.yml"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  upload-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git pull
      - run: tar -czf zenn.tar.gz -C zenn .
      - uses: softprops/action-gh-release@v2
        with:
          files: zenn.tar.gz
          tag_name: latest
      - run: tar -czf dist.tar.gz -C dist .
      - uses: softprops/action-gh-release@v2
        with:
          files: dist.tar.gz
          tag_name: latest
