name: update-zenn-icons

on:
  schedule:
    - cron: "0 21 1 * *"
  push:
    branches:
      - main
    paths:
      - "**/*.py"
      - "requirements.txt"
      - ".github/workflows/zenn-icons-update.yml"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  crawl-zenn-icons:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v2
        with:
          python-version: "3.13"
      - run: pip install -r requirements.txt
      - run: python main.py
        env:
          CI: "true"

      - name: Commit
        continue-on-error: true
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Update"
          git push origin main

  upload-files:
    needs: crawl-zenn-icons
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git pull
      - run: tar -czf zenn-icons.tar.gz -C images .
      - uses: softprops/action-gh-release@v2
        with:
          files: zenn-icons.tar.gz
          tag_name: latest
      - run: tar -czf dist.tar.gz -C dist .
      - uses: softprops/action-gh-release@v2
        with:
          files: dist.tar.gz
          tag_name: latest
